# name: Publish
# on:
#   push:
#     # only run when pushing tags
#     tags:
#       - "*"

# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#     steps:
#       - uses: actions/checkout@v4
#       - uses: oven-sh/setup-bun@v2
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 22.x
#           registry-url: "https://registry.npmjs.org"
#       - name: build
#         run: |
#           bun install
#           make build
#       - name: Publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#         run: |
#           npm publish --provenance --access public
